<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartBackendServices.TokenClient\SmartBackendServices.TokenClient.csproj" />
  </ItemGroup>
</Project>
